# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'InstagramTestApp' do
    pod "AFNetworking", "~> 2.0"
    pod 'InstagramKit', '3.5.0'
    pod 'SVPullToRefresh'
    pod 'SSKeychain'
    pod "MagicalRecord"
end

target 'InstagramTestAppTests' do

end

